name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: configure
    #   run: ./configure

    - name: Install dependencies & compile custom policy
      run: make build

    - name: Publish custom policy
      run: make publish

    - name: Releases custome policy
      run: make release
